const TWO_LETTER_CODES = {
    'Archer Queen': 'aq',
    'Archers': 'ac',
    'Arrows': 'ar',
    'Baby Dragon': 'bd',
    'Balloon': 'bn',
    'Bandit': 'ba',
    'Barbarian Barrel': 'bb',
    'Barbarian Hut': 'bu',
    'Barbarians': 'bs',
    'Barperians': 'ba',
    'Bats': 'ba',
    'Battle Healer': 'bh',
    'Battle Ram': 'br',
    'Bomb Tower': 'bt',
    'Bomber': 'bo',
    'Bowler': 'bw',
    'Cannon': 'cn',
    'Cannon Cart': 'cc',
    'Clone': 'cl',
    'Dark Prince': 'dp',
    'Dart Goblin': 'dg',
    'Earthquake': 'eq',
    'Electro Dragon': 'ed',
    'Electro Giant': 'eg',
    'Electro Spirit': 'es',
    'Electro Wizard': 'ew',
    'Elite Barbarians': 'eb',
    'Elixir Collector': 'ec',
    'Elixir Golem': 'el',
    'Executioner': 'ex',
    'Fire Spirit': 'fs',
    'Fireball': 'fb',
    'Firecracker': 'fi',
    'Fisherman': 'fn',
    'Flying Machine': 'fm',
    'Freeze': 'fz',
    'Furnace': 'fu',
    'Giant': 'gi',
    'Giant Skeleton': 'gs',
    'Giant Snowball': 'sn',
    'Goblin Barrel': 'gb',
    'Goblin Cage': 'gc',
    'Goblin Drill': 'gd',
    'Goblin Gang': 'ga',
    'Goblin Giant': 'gg',
    'Goblin Hut': 'gh',
    'Goblins': 'go',
    'Golden Knight': 'gk',
    'Golem': 'gm',
    'Graveyard': 'gy',
    'Guards': 'gu',
    'Heal Spirit': 'hs',
    'Hog Rider': 'hr',
    'Hunter': 'hu',
    'Ice Golem': 'ig',
    'Ice Spirit': 'is',
    'Ice Wizard': 'iw',
    'Inferno Dragon': 'id',
    'Inferno Tower': 'it',
    'Knight': 'kn',
    'Lava Hound': 'lh',
    'Lightning': 'lk',
    'Little Prince': 'lp',
    'Lumberjack': 'lj',
    'Magic Archer': 'ma',
    'Mega Knight': 'mk',
    'Mega Minion': 'mm',
    'Mighty Miner': 'mm',
    'Miner': 'mi',
    'Mini P.E.K.K.A': 'mp',
    'Minion Horde': 'mh',
    'Minions': 'mi',
    'Mirror': 'mr',
    'Monk': 'mo',
    'Mortar': 'mo',
    'Mother Witch': 'mw',
    'Musketeer': 'mu',
    'Night Witch': 'nw',
    'P.E.K.K.A': 'pk',
    'Phoenix': 'ph',
    'Poison': 'po',
    'Prince': 'pe',
    'Princess': 'pr',
    'Rage': 'ra',
    'Ram Rider': 'rr',
    'Rascals': 'rs',
    'Rocket': 'rk',
    'Royal Delivery': 'rd',
    'Royal Ghost': 'ro',
    'Royal Giant': 'rg',
    'Royal Hogs': 'rh',
    'Royal Recruits': 'rc',
    'Skeleton Army': 'sa',
    'Skeleton Barrel': 'sb',
    'Skeleton Dragons': 'sd',
    'Skeleton King': 'sk',
    'Skeletons': 'ss',
    'Sparky': 'sp',
    'Spear Goblins': 'sg',
    'Tesla': 'te',
    'The Log': 'lo',
    'Three Musketeers': '3m',
    'Tombstone': 'to',
    'Tornado': 'to',
    'Valkyrie': 'va',
    'Void': 'vd',
    'Wall Breakers': 'wb',
    'Witch': 'wi',
    'Wizard': 'wd',
    'X-Bow': 'xb',
    'Zap': 'za',
    'Zappies': 'zp',
};

// UNRESOLVED COLLISIONS (Manual Fix Needed):
[
  {
    "card": "Bandit",
    "code": "ba"
  },
  {
    "card": "Barperians",
    "code": "ba"
  },
  {
    "card": "Miner",
    "code": "mi"
  },
  {
    "card": "Tombstone",
    "code": "to"
  }
]